openapi: 3.2.0
info:
  title: IMS Metadata API
  description: This API returns information about IMS tags and the values that they measure.
  contact:
    name: Omnia Plant Team
    email: omniaindiot@equinor.com
  version: v1.3
servers:
- url: https://api.gateway.equinor.com/plant/ims-metadata
- url: https://api-ncc.gateway.equinor.com/plant/ims-metadata
security:
- {}
- apiKeyHeader: []
- apiKeyQuery: []
tags:
- name: IMS Metadata API
paths:
  /{plant}/{tag}:
    get:
      operationId: get-plant-tag
      summary: Gets a specific tag specified by plant and tag name
      description: Gets a specific tag specified by plant and tag name.
      parameters:
      - name: plant
        in: path
        required: true
        description: The name of the plant
        schema:
          type: string
      - name: tag
        in: path
        required: true
        description: The name of the tag
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetadataItemResponse_v2'
              example:
                links:
                - relationship: string
                  reference: string
                data:
                  id: string
                  uid: string
                  imsType: string
                  systemCode: string
                  recordID: string
                  plantSAPCode: string
                  plantSTIDCode: string
                  denyDataShare: string
                  tag: string
                  terminal: string
                  isDefaultTerminal: true
                  description: string
                  engUnits: string
                  standardUnit: string
                  source: string
                  type: string
                  sourceTag: string
                  stepped: true
                  changeDate: string
                  creationDate: string
                  currentValueDate: string
                  plantArea: string
                  significantDigit: string
                  maxTimeInterval: string
                  fieldId: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
              example:
                statusCode: 0
                message: string
                traceId: string
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
              example:
                statusCode: 0
                message: string
                traceId: string
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
              example:
                statusCode: 0
                message: string
                traceId: string
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
              example:
                statusCode: 0
                message: string
                traceId: string
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
              example:
                statusCode: 0
                message: string
                traceId: string
      x-source: https://api.equinor.com/developer/apis/ims-metadata-api-v1-3/operations/get-plant-tag?api-version=2022-04-01-preview
      tags:
      - IMS Metadata API
  /{plant}:
    get:
      operationId: get-plant
      summary: List tags for the specified plant
      description: List tags for the specified plant.
      parameters:
      - name: plant
        in: path
        required: true
        description: The plant whose tags to list.
        schema:
          type: string
      - name: limit
        in: query
        required: false
        description: Specifies how many records you want returned. Cannot be more than 1000.
        schema:
          type: number
      - name: continuationToken
        in: query
        required: false
        description: Can be passed to retrieve the next page of results if there are any.
        schema:
          type: string
      - name: id
        in: query
        required: false
        description: Filters the tag result on the 'id' field. Can be specified multiple times to include more matches.
        schema:
          type: string
      - name: uid
        in: query
        required: false
        description: Filters the tag result on the 'uid' field. Can be specified multiple times to include more matches.
        schema:
          type: string
      - name: imsType
        in: query
        required: false
        description: Filters the tag result on the 'imsType' field. Can be specified multiple times to include more matches.
        schema:
          type: string
      - name: systemCode
        in: query
        required: false
        description: Filters the tag result on the 'systemCode' field. Can be specified multiple times to include more matches.
        schema:
          type: string
      - name: recordId
        in: query
        required: false
        description: Filters the tag result on the 'recordId' field. Can be specified multiple times to include more matches.
        schema:
          type: string
      - name: plantSapCode
        in: query
        required: false
        description: Filters the tag result on the 'plantSapCode' field. Can be specified multiple times to include more matches.
        schema:
          type: string
      - name: plantStidCode
        in: query
        required: false
        description: Filters the tag result on the 'plantStidCode' field. Can be specified multiple times to include more matches.
        schema:
          type: string
      - name: denyDataShare
        in: query
        required: false
        description: Filters the tag result on the 'denyDataShare' field. Can be specified multiple times to include more matches.
        schema:
          type: string
      - name: tag
        in: query
        required: false
        description: Filters the tag result on the 'tag' field. Can be specified multiple times to include more matches.
        schema:
          type: string
      - name: terminal
        in: query
        required: false
        description: Filters the tag result on the 'terminal' field. Can be specified multiple times to include more matches.
        schema:
          type: string
      - name: isDefaultTerminal
        in: query
        required: false
        description: Filters the tag result on the 'isDefaultTerminal' field. Can be specified multiple times to include more matches.
        schema:
          type: boolean
      - name: description
        in: query
        required: false
        description: Filters the tag result on the 'description' field. Can be specified multiple times to include more matches.
        schema:
          type: string
      - name: engUnits
        in: query
        required: false
        description: Filters the tag result on the 'engUnits' field. Can be specified multiple times to include more matches.
        schema:
          type: string
      - name: standardUnit
        in: query
        required: false
        description: Filters the tag result on the 'standardUnit' field. Can be specified multiple times to include more matches.
        schema:
          type: string
      - name: source
        in: query
        required: false
        description: Filters the tag result on the 'source' field. Can be specified multiple times to include more matches.
        schema:
          type: string
      - name: type
        in: query
        required: false
        description: Filters the tag result on the 'type' field. Can be specified multiple times to include more matches.
        schema:
          type: string
      - name: sourceTag
        in: query
        required: false
        description: Filters the tag result on the 'sourceTag' field. Can be specified multiple times to include more matches.
        schema:
          type: string
      - name: stepped
        in: query
        required: false
        description: Filters the tag result on the 'stepped' field. Can be specified multiple times to include more matches.
        schema:
          type: boolean
      - name: changeDate
        in: query
        required: false
        description: Format - date-time (as date-time in RFC3339). Filters the tag result on the 'changeDate' field. Can be specified multiple times to include more matches.
        schema:
          type: string
      - name: creationDate
        in: query
        required: false
        description: Format - date-time (as date-time in RFC3339). Filters the tag result on the 'creationDate' field. Can be specified multiple times to include more matches.
        schema:
          type: string
      - name: currentValueDate
        in: query
        required: false
        description: Format - date-time (as date-time in RFC3339). Filters the tag result on the 'currentValueDate' field. Can be specified multiple times to include more matches.
        schema:
          type: string
      - name: plantArea
        in: query
        required: false
        description: Filters the tag result on the 'plantArea' field. Can be specified multiple times to include more matches.
        schema:
          type: string
      - name: significantDigit
        in: query
        required: false
        description: Filters the tag result on the 'significantDigit' field. Can be specified multiple times to include more matches.
        schema:
          type: string
      - name: maxTimeInterval
        in: query
        required: false
        description: Filters the tag result on the 'maxTimeInterval' field. Can be specified multiple times to include more matches.
        schema:
          type: string
      - name: fieldId
        in: query
        required: false
        description: Filters the tag result on the 'fieldId' field. Can be specified multiple times to include more matches.
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetadataPagedResponse_v2'
              example:
                links:
                - relationship: string
                  reference: string
                data:
                  items:
                  - id: string
                    uid: string
                    imsType: string
                    systemCode: string
                    recordID: string
                    plantSAPCode: string
                    plantSTIDCode: string
                    denyDataShare: string
                    tag: string
                    terminal: string
                    isDefaultTerminal: true
                    description: string
                    engUnits: string
                    standardUnit: string
                    source: string
                    type: string
                    sourceTag: string
                    stepped: true
                    changeDate: string
                    creationDate: string
                    currentValueDate: string
                    plantArea: string
                    significantDigit: string
                    maxTimeInterval: string
                    fieldId: string
                count: 0
                continuationToken: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
              example:
                statusCode: 0
                message: string
                traceId: string
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
              example:
                statusCode: 0
                message: string
                traceId: string
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
              example:
                statusCode: 0
                message: string
                traceId: string
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
              example:
                statusCode: 0
                message: string
                traceId: string
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
              example:
                statusCode: 0
                message: string
                traceId: string
      x-source: https://api.equinor.com/developer/apis/ims-metadata-api-v1-3/operations/get-plant?api-version=2022-04-01-preview
      tags:
      - IMS Metadata API
  /:
    get:
      operationId: get
      summary: Lists all tags for all plants
      description: Lists all tags for all plants.
      parameters:
      - name: limit
        in: query
        required: false
        description: Specifies how many records you want returned. Cannot be more than 1000.
        schema:
          type: number
      - name: continuationToken
        in: query
        required: false
        description: Can be passed to retrieve the next page of results if there are any.
        schema:
          type: string
      - name: id
        in: query
        required: false
        description: Filters the tag result on the 'id' field. Can be specified multiple times to include more matches.
        schema:
          type: string
      - name: uid
        in: query
        required: false
        description: Filters the tag result on the 'uid' field. Can be specified multiple times to include more matches.
        schema:
          type: string
      - name: imsType
        in: query
        required: false
        description: Filters the tag result on the 'imsType' field. Can be specified multiple times to include more matches.
        schema:
          type: string
      - name: systemCode
        in: query
        required: false
        description: Filters the tag result on the 'systemCode' field. Can be specified multiple times to include more matches.
        schema:
          type: string
      - name: recordId
        in: query
        required: false
        description: Filters the tag result on the 'recordId' field. Can be specified multiple times to include more matches.
        schema:
          type: string
      - name: plantSapCode
        in: query
        required: false
        description: Filters the tag result on the 'plantSapCode' field. Can be specified multiple times to include more matches.
        schema:
          type: string
      - name: plantStidCode
        in: query
        required: false
        description: Filters the tag result on the 'plantStidCode' field. Can be specified multiple times to include more matches.
        schema:
          type: string
      - name: denyDataShare
        in: query
        required: false
        description: Filters the tag result on the 'denyDataShare' field. Can be specified multiple times to include more matches.
        schema:
          type: string
      - name: tag
        in: query
        required: false
        description: Filters the tag result on the 'tag' field. Can be specified multiple times to include more matches.
        schema:
          type: string
      - name: terminal
        in: query
        required: false
        description: Filters the tag result on the 'terminal' field. Can be specified multiple times to include more matches.
        schema:
          type: string
      - name: isDefaultTerminal
        in: query
        required: false
        description: Filters the tag result on the 'isDefaultTerminal' field. Can be specified multiple times to include more matches.
        schema:
          type: boolean
      - name: description
        in: query
        required: false
        description: Filters the tag result on the 'description' field. Can be specified multiple times to include more matches.
        schema:
          type: string
      - name: engUnits
        in: query
        required: false
        description: Filters the tag result on the 'engUnits' field. Can be specified multiple times to include more matches.
        schema:
          type: string
      - name: standardUnit
        in: query
        required: false
        description: Filters the tag result on the 'standardUnit' field. Can be specified multiple times to include more matches.
        schema:
          type: string
      - name: source
        in: query
        required: false
        description: Filters the tag result on the 'source' field. Can be specified multiple times to include more matches.
        schema:
          type: string
      - name: type
        in: query
        required: false
        description: Filters the tag result on the 'type' field. Can be specified multiple times to include more matches.
        schema:
          type: string
      - name: sourceTag
        in: query
        required: false
        description: Filters the tag result on the 'sourceTag' field. Can be specified multiple times to include more matches.
        schema:
          type: string
      - name: stepped
        in: query
        required: false
        description: Filters the tag result on the 'stepped' field. Can be specified multiple times to include more matches.
        schema:
          type: boolean
      - name: changeDate
        in: query
        required: false
        description: Format - date-time (as date-time in RFC3339). Filters the tag result on the 'changeDate' field. Can be specified multiple times to include more matches.
        schema:
          type: string
      - name: creationDate
        in: query
        required: false
        description: Format - date-time (as date-time in RFC3339). Filters the tag result on the 'creationDate' field. Can be specified multiple times to include more matches.
        schema:
          type: string
      - name: currentValueDate
        in: query
        required: false
        description: Format - date-time (as date-time in RFC3339). Filters the tag result on the 'currentValueDate' field. Can be specified multiple times to include more matches.
        schema:
          type: string
      - name: plantArea
        in: query
        required: false
        description: Filters the tag result on the 'plantArea' field. Can be specified multiple times to include more matches.
        schema:
          type: string
      - name: significantDigit
        in: query
        required: false
        description: Filters the tag result on the 'significantDigit' field. Can be specified multiple times to include more matches.
        schema:
          type: string
      - name: maxTimeInterval
        in: query
        required: false
        description: Filters the tag result on the 'maxTimeInterval' field. Can be specified multiple times to include more matches.
        schema:
          type: string
      - name: fieldId
        in: query
        required: false
        description: Filters the tag result on the 'fieldId' field. Can be specified multiple times to include more matches.
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetadataPagedResponse_v2'
              example:
                links:
                - relationship: string
                  reference: string
                data:
                  items:
                  - id: string
                    uid: string
                    imsType: string
                    systemCode: string
                    recordID: string
                    plantSAPCode: string
                    plantSTIDCode: string
                    denyDataShare: string
                    tag: string
                    terminal: string
                    isDefaultTerminal: true
                    description: string
                    engUnits: string
                    standardUnit: string
                    source: string
                    type: string
                    sourceTag: string
                    stepped: true
                    changeDate: string
                    creationDate: string
                    currentValueDate: string
                    plantArea: string
                    significantDigit: string
                    maxTimeInterval: string
                    fieldId: string
                count: 0
                continuationToken: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
              example:
                statusCode: 0
                message: string
                traceId: string
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
              example:
                statusCode: 0
                message: string
                traceId: string
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
              example:
                statusCode: 0
                message: string
                traceId: string
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
              example:
                statusCode: 0
                message: string
                traceId: string
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
              example:
                statusCode: 0
                message: string
                traceId: string
      x-source: https://api.equinor.com/developer/apis/ims-metadata-api-v1-3/operations/get?api-version=2022-04-01-preview
      tags:
      - IMS Metadata API
    post:
      operationId: post
      summary: Provides endpoint to search for and list metadata by a list of tags, uid etc
      description: Provides endpoint to search for and list metadata by a list of tags, uid etc.
      parameters:
      - name: limit
        in: query
        required: false
        description: Specifies how many records you want returned. Cannot be more than 1000.
        schema:
          type: number
      - name: continuationToken
        in: query
        required: false
        description: Can be passed to retrieve the next page of results if there are any.
        schema:
          type: string
      - name: id
        in: query
        required: false
        description: Filters the tag result on the 'id' field. Can be specified multiple times to include more matches.
        schema:
          type: string
      - name: uid
        in: query
        required: false
        description: Filters the tag result on the 'uid' field. Can be specified multiple times to include more matches.
        schema:
          type: string
      - name: imsType
        in: query
        required: false
        description: Filters the tag result on the 'imsType' field. Can be specified multiple times to include more matches.
        schema:
          type: string
      - name: systemCode
        in: query
        required: false
        description: Filters the tag result on the 'systemCode' field. Can be specified multiple times to include more matches.
        schema:
          type: string
      - name: recordId
        in: query
        required: false
        description: Filters the tag result on the 'recordId' field. Can be specified multiple times to include more matches.
        schema:
          type: string
      - name: plantSapCode
        in: query
        required: false
        description: Filters the tag result on the 'plantSapCode' field. Can be specified multiple times to include more matches.
        schema:
          type: string
      - name: plantStidCode
        in: query
        required: false
        description: Filters the tag result on the 'plantStidCode' field. Can be specified multiple times to include more matches.
        schema:
          type: string
      - name: denyDataShare
        in: query
        required: false
        description: Filters the tag result on the 'denyDataShare' field. Can be specified multiple times to include more matches.
        schema:
          type: string
      - name: tag
        in: query
        required: false
        description: Filters the tag result on the 'tag' field. Can be specified multiple times to include more matches.
        schema:
          type: string
      - name: terminal
        in: query
        required: false
        description: Filters the tag result on the 'terminal' field. Can be specified multiple times to include more matches.
        schema:
          type: string
      - name: isDefaultTerminal
        in: query
        required: false
        description: Filters the tag result on the 'isDefaultTerminal' field. Can be specified multiple times to include more matches.
        schema:
          type: boolean
      - name: description
        in: query
        required: false
        description: Filters the tag result on the 'description' field. Can be specified multiple times to include more matches.
        schema:
          type: string
      - name: engUnits
        in: query
        required: false
        description: Filters the tag result on the 'engUnits' field. Can be specified multiple times to include more matches.
        schema:
          type: string
      - name: standardUnit
        in: query
        required: false
        description: Filters the tag result on the 'standardUnit' field. Can be specified multiple times to include more matches.
        schema:
          type: string
      - name: source
        in: query
        required: false
        description: Filters the tag result on the 'source' field. Can be specified multiple times to include more matches.
        schema:
          type: string
      - name: type
        in: query
        required: false
        description: Filters the tag result on the 'type' field. Can be specified multiple times to include more matches.
        schema:
          type: string
      - name: sourceTag
        in: query
        required: false
        description: Filters the tag result on the 'sourceTag' field. Can be specified multiple times to include more matches.
        schema:
          type: string
      - name: stepped
        in: query
        required: false
        description: Filters the tag result on the 'stepped' field. Can be specified multiple times to include more matches.
        schema:
          type: boolean
      - name: changeDate
        in: query
        required: false
        description: Format - date-time (as date-time in RFC3339). Filters the tag result on the 'changeDate' field. Can be specified multiple times to include more matches.
        schema:
          type: string
      - name: creationDate
        in: query
        required: false
        description: Format - date-time (as date-time in RFC3339). Filters the tag result on the 'creationDate' field. Can be specified multiple times to include more matches.
        schema:
          type: string
      - name: currentValueDate
        in: query
        required: false
        description: Format - date-time (as date-time in RFC3339). Filters the tag result on the 'currentValueDate' field. Can be specified multiple times to include more matches.
        schema:
          type: string
      - name: plantArea
        in: query
        required: false
        description: Filters the tag result on the 'plantArea' field. Can be specified multiple times to include more matches.
        schema:
          type: string
      - name: significantDigit
        in: query
        required: false
        description: Filters the tag result on the 'significantDigit' field. Can be specified multiple times to include more matches.
        schema:
          type: string
      - name: maxTimeInterval
        in: query
        required: false
        description: Filters the tag result on the 'maxTimeInterval' field. Can be specified multiple times to include more matches.
        schema:
          type: string
      - name: fieldId
        in: query
        required: false
        description: Filters the tag result on the 'fieldId' field. Can be specified multiple times to include more matches.
        schema:
          type: string
      requestBody:
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/PostRequest-27'
            example:
            - id: string
              uid: string
              imsType: string
              systemCode: string
              recordId: string
              plantSapCode: string
              plantStidCode: string
              denyDataShare: string
              tag: string
              terminal: string
              isDefaultTerminal: true
              description: string
              engUnits: string
              standardUnit: string
              source: string
              type: string
              sourceTag: string
              stepped: true
              changeDate: string
              creationDate: string
              currentValueDate: string
              plantArea: string
              significantDigit: string
              maxTimeInterval: string
              fieldId: string
              isDeleted: true
          application/json:
            schema:
              $ref: '#/components/schemas/PostRequest-28'
            example:
            - id: string
              uid: string
              imsType: string
              systemCode: string
              recordId: string
              plantSapCode: string
              plantStidCode: string
              denyDataShare: string
              tag: string
              terminal: string
              isDefaultTerminal: true
              description: string
              engUnits: string
              standardUnit: string
              source: string
              type: string
              sourceTag: string
              stepped: true
              changeDate: string
              creationDate: string
              currentValueDate: string
              plantArea: string
              significantDigit: string
              maxTimeInterval: string
              fieldId: string
              isDeleted: true
          text/json:
            schema:
              $ref: '#/components/schemas/PostRequest-29'
            example:
            - id: string
              uid: string
              imsType: string
              systemCode: string
              recordId: string
              plantSapCode: string
              plantStidCode: string
              denyDataShare: string
              tag: string
              terminal: string
              isDefaultTerminal: true
              description: string
              engUnits: string
              standardUnit: string
              source: string
              type: string
              sourceTag: string
              stepped: true
              changeDate: string
              creationDate: string
              currentValueDate: string
              plantArea: string
              significantDigit: string
              maxTimeInterval: string
              fieldId: string
              isDeleted: true
          application/*+json:
            schema:
              $ref: '#/components/schemas/PostRequest-30'
            example:
            - id: string
              uid: string
              imsType: string
              systemCode: string
              recordId: string
              plantSapCode: string
              plantStidCode: string
              denyDataShare: string
              tag: string
              terminal: string
              isDefaultTerminal: true
              description: string
              engUnits: string
              standardUnit: string
              source: string
              type: string
              sourceTag: string
              stepped: true
              changeDate: string
              creationDate: string
              currentValueDate: string
              plantArea: string
              significantDigit: string
              maxTimeInterval: string
              fieldId: string
              isDeleted: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetadataPagedResponse_v2'
              example:
                links:
                - relationship: string
                  reference: string
                data:
                  items:
                  - id: string
                    uid: string
                    imsType: string
                    systemCode: string
                    recordID: string
                    plantSAPCode: string
                    plantSTIDCode: string
                    denyDataShare: string
                    tag: string
                    terminal: string
                    isDefaultTerminal: true
                    description: string
                    engUnits: string
                    standardUnit: string
                    source: string
                    type: string
                    sourceTag: string
                    stepped: true
                    changeDate: string
                    creationDate: string
                    currentValueDate: string
                    plantArea: string
                    significantDigit: string
                    maxTimeInterval: string
                    fieldId: string
                count: 0
                continuationToken: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
              example:
                statusCode: 0
                message: string
                traceId: string
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
              example:
                statusCode: 0
                message: string
                traceId: string
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
              example:
                statusCode: 0
                message: string
                traceId: string
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
              example:
                statusCode: 0
                message: string
                traceId: string
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
              example:
                statusCode: 0
                message: string
                traceId: string
      x-source: https://api.equinor.com/developer/apis/ims-metadata-api-v1-3/operations/post?api-version=2022-04-01-preview
      tags:
      - IMS Metadata API
components:
  schemas:
    PostRequest-29:
      type: array
      items:
        $ref: '#/components/schemas/MetadataSearchModel'
      x-apim-inline: true
    PostRequest-30:
      type: array
      items:
        $ref: '#/components/schemas/MetadataSearchModel'
      x-apim-inline: true
    MetadataPagedResponse_v2:
      type: object
      properties:
        links:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/Hyperlink'
          description: Links that can be used to get related resources
        data:
          $ref: '#/components/schemas/MetadataList_v2'
        count:
          type:
          - integer
          - 'null'
          description: Total amount of results in the query
          format: int64
        continuationToken:
          type:
          - string
          - 'null'
          description: Continuation token used to get the next page
      additionalProperties: false
      description: Metadata response model with continuation token
    MetadataItem_v2:
      type: object
      properties:
        id:
          type:
          - string
          - 'null'
          description: SHA1 hash of the UId
        uid:
          type:
          - string
          - 'null'
          description: A unique id of the tag (plant + a counter)
        imsType:
          type:
          - string
          - 'null'
          description: The type of this IMS tag
        systemCode:
          type:
          - string
          - 'null'
          description: The name of the IMS System
        recordID:
          type:
          - string
          - 'null'
          description: The ID of the record from the IMS system
        plantSAPCode:
          type:
          - string
          - 'null'
          description: The SAP code of the plant
        plantSTIDCode:
          type:
          - string
          - 'null'
          description: The STID code of the plant
        denyDataShare:
          type:
          - string
          - 'null'
          description: Reason for denied access where null means access allowed
        tag:
          type:
          - string
          - 'null'
          description: The name of the tag
        terminal:
          type:
          - string
          - 'null'
          description: The name of the terminal
        isDefaultTerminal:
          type:
          - boolean
          - 'null'
          description: Is the terminal default
        description:
          type:
          - string
          - 'null'
          description: The description of the tag
        engUnits:
          type:
          - string
          - 'null'
          description: The measurement unit of the tag in English
        standardUnit:
          type:
          - string
          - 'null'
          description: The standard unit of measurement from commonlib
        source:
          type:
          - string
          - 'null'
          description: The source of the data
        type:
          type:
          - string
          - 'null'
          description: The type of the signal data
        sourceTag:
          type:
          - string
          - 'null'
          description: The original tag name if the signal data comes from another tag
        stepped:
          type:
          - boolean
          - 'null'
          description: Whether or not the signal data is stepped or raw
        changeDate:
          type:
          - string
          - 'null'
          description: The date/time when this tag was last changed
          format: date-time
        creationDate:
          type:
          - string
          - 'null'
          description: The date/time when this tag was created
          format: date-time
        currentValueDate:
          type:
          - string
          - 'null'
          description: The date/time of the last/current value of the tag
          format: date-time
        plantArea:
          type:
          - string
          - 'null'
          description: The area of the plant
        significantDigit:
          type:
          - string
          - 'null'
          description: A string specifying the significant digits of the data-points
        maxTimeInterval:
          type:
          - string
          - 'null'
          description: The maximum time interval in which the data-points are valid
        fieldId:
          type:
          - string
          - 'null'
          description: The field ID
      additionalProperties: false
      description: The metadata information of a tag
    PostRequest-27:
      type: array
      items:
        $ref: '#/components/schemas/MetadataSearchModel'
      x-apim-inline: true
    PostRequest-28:
      type: array
      items:
        $ref: '#/components/schemas/MetadataSearchModel'
      x-apim-inline: true
    MetadataSearchModel:
      type: object
      properties:
        id:
          type:
          - string
          - 'null'
          description: SHA1 hash of the UId
        uid:
          type:
          - string
          - 'null'
          description: A unique id of the tag (plant + a counter + map)
        imsType:
          type:
          - string
          - 'null'
          description: The type of this IMS tag
        systemCode:
          type:
          - string
          - 'null'
          description: The name of the IMS System
        recordId:
          type:
          - string
          - 'null'
          description: The ID of the record from the IMS system
        plantSapCode:
          type:
          - string
          - 'null'
          description: The SAP code of the plant
        plantStidCode:
          type:
          - string
          - 'null'
          description: The STID code of the plant
        denyDataShare:
          type:
          - string
          - 'null'
          description: Reason for denied access where null means access allowed
        tag:
          type:
          - string
          - 'null'
          description: The name of the tag
        terminal:
          type:
          - string
          - 'null'
          description: The name of the map
        isDefaultTerminal:
          type:
          - boolean
          - 'null'
          description: Whether or not the map is default
        description:
          type:
          - string
          - 'null'
          description: The description of the tag
        engUnits:
          type:
          - string
          - 'null'
          description: The measurement unit of the tag in English
        standardUnit:
          type:
          - string
          - 'null'
          description: The standard unit of measurement from commonlib
        source:
          type:
          - string
          - 'null'
          description: The source of the data
        type:
          type:
          - string
          - 'null'
          description: The type of the signal data
        sourceTag:
          type:
          - string
          - 'null'
          description: The original tag name if the signal data comes from another tag
        stepped:
          type:
          - boolean
          - 'null'
          description: Whether or not the signal data is stepped or raw
        changeDate:
          type:
          - string
          - 'null'
          description: The date/time when this tag was last changed
          format: date-time
        creationDate:
          type:
          - string
          - 'null'
          description: The date/time when this tag was created
          format: date-time
        currentValueDate:
          type:
          - string
          - 'null'
          description: The date/time when this tag was created
          format: date-time
        plantArea:
          type:
          - string
          - 'null'
          description: The area of the plant
        significantDigit:
          type:
          - string
          - 'null'
          description: A string specifying the significant digits of the data-points
        maxTimeInterval:
          type:
          - string
          - 'null'
          description: The maximum time interval in which the data-points are valid
        fieldId:
          type:
          - string
          - 'null'
          description: The field ID
        isDeleted:
          type:
          - boolean
          - 'null'
      additionalProperties: false
      description: The metadata information of a tag
    MetadataList_v2:
      type: object
      properties:
        items:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/MetadataItem_v2'
          description: The metadata result items
      additionalProperties: false
      description: The metadata result
    ErrorDetails:
      type: object
      properties:
        statusCode:
          type: integer
          description: The HTTP status code
          format: int32
        message:
          type:
          - string
          - 'null'
          description: The error message
        traceId:
          type:
          - string
          - 'null'
          description: Trace ID that can be used by support to determine root cause
      additionalProperties: false
      description: Describes the error returned by the server
    Hyperlink:
      type: object
      properties:
        relationship:
          type:
          - string
          - 'null'
          description: The relationship the current resource has to the reference resource
        reference:
          type:
          - string
          - 'null'
          description: The reference resource hyperlink
          format: uri
      additionalProperties: false
      description: Holds a hyperlink to a resource and what relationship the current resource has to it
    MetadataItemResponse_v2:
      type: object
      properties:
        links:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/Hyperlink'
          description: Links that can be used to get related resources
        data:
          $ref: '#/components/schemas/MetadataItem_v2'
      additionalProperties: false
      description: Metadata list response model
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
x-generated-from: apim-developer-portal-data
x-source: https://api.equinor.com/api-details#api=ims-metadata-api-v1-3
x-generated-note: The anonymous APIM export at https://api.equinor.com/developer/apis/ims-metadata-api-v1-3?export=true&format=openapi%2Bjson returns this document with empty paths; paths were assembled verbatim (by script) from the same portal's anonymous operations and schemas endpoints, saved in openapi/_original/.
