openapi: 3.2.0
info:
  title: Alarm Events API
  description: API for Alarm and Events
  contact:
    name: Omnia Industrial IoT team
    email: OmniaIndIoT@equinor.com
  version: v1
servers:
- url: https://api.gateway.equinor.com/iiot/ae
- url: https://api-ncc.gateway.equinor.com/iiot/ae
security:
- {}
- apiKeyHeader: []
- apiKeyQuery: []
tags:
- name: Events
paths:
  /events/{facility}:
    get:
      operationId: GetEvents
      summary: Retrieves a list of all events.
      description: Retrieves a list of all events. Parameters can be used to select a subset of events. Note that maximum result set size is 100.000 items.
      parameters:
      - name: facility
        in: path
        required: true
        description: Name of the facility which to retrieve data.
        schema:
          type: string
      - name: sourceName
        in: query
        required: true
        description: Source name of event from which to retrieve data.
        schema:
          type: string
      - name: startTime
        in: query
        required: false
        description: Format - date-time (as date-time in RFC3339). Start of data window. Defaults to 1970.
        schema:
          type: string
      - name: endTime
        in: query
        required: false
        description: Format - date-time (as date-time in RFC3339). End of data window. Defaults to now.
        schema:
          type: string
      - name: sort
        in: query
        required: false
        description: Defaults to asc
        schema:
          type: string
      - name: includeOtherFields
        in: query
        required: false
        description: Determines whether or not to include other fields.
        schema:
          type: boolean
      - name: description
        in: query
        required: false
        description: Filters the tag result on the 'description' field. Can be specified multiple times to include more matches.
        schema:
          type: string
      - name: eventType
        in: query
        required: false
        description: Filters the tag result on the 'eventType' field. Can be specified multiple times to include more matches.
        schema:
          type: string
      - name: eventCategory
        in: query
        required: false
        description: Filters the tag result on the 'eventCategory' field. Can be specified multiple times to include more matches.
        schema:
          type: string
      - name: message
        in: query
        required: false
        description: Filters the tag result on the 'message' field. Can be specified multiple times to include more matches.
        schema:
          type: string
      - name: severity
        in: query
        required: false
        description: Format - int32. Filters the tag result on the 'severity' field. Can be specified multiple times to include more matches.
        schema:
          type: integer
      - name: priority
        in: query
        required: false
        description: Format - int32. Filters the tag result on the 'priority' field. Can be specified multiple times to include more matches.
        schema:
          type: integer
      - name: condition
        in: query
        required: false
        description: Filters the tag result on the 'condition' field. Can be specified multiple times to include more matches.
        schema:
          type: string
      - name: alarmState
        in: query
        required: false
        description: Filters the tag result on the 'alarmState' field. Can be specified multiple times to include more matches.
        schema:
          type: string
      - name: ackedState
        in: query
        required: false
        description: Filters the tag result on the 'ackedState' field. Can be specified multiple times to include more matches.
        schema:
          type: boolean
      - name: activeState
        in: query
        required: false
        description: Filters the tag result on the 'activeState' field. Can be specified multiple times to include more matches.
        schema:
          type: boolean
      - name: suppressedOrShelved
        in: query
        required: false
        description: Filters the tag result on the 'suppressedOrShelved' field. Can be specified multiple times to include more matches.
        schema:
          type: boolean
      - name: node
        in: query
        required: false
        description: Filters the tag result on the 'node' field. Can be specified multiple times to include more matches.
        schema:
          type: string
      - name: processArea
        in: query
        required: false
        description: Filters the tag result on the 'processArea' field. Can be specified multiple times to include more matches.
        schema:
          type: string
      - name: actiontime
        in: query
        required: false
        description: Format - date-time (as date-time in RFC3339). Filters the tag result on the 'actiontime' field. Can be specified multiple times to include more matches.
        schema:
          type: string
      - name: limit
        in: query
        required: false
        description: Specifies how many records you want returned. Cannot be more than 100000.
        schema:
          type: number
      - name: continuationToken
        in: query
        required: false
        description: Can be passed to retrieve the next page of results if there are any.
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventDto'
              example:
                statusCode: 0
                message: string
                traceId: string
                items:
                - timestamp: string
                  sourceName: string
                  description: string
                  eventType: string
                  eventCategory: string
                  message: string
                  severity: 0
                  priority: 0
                  condition: string
                  alarmState: string
                  ackedState: true
                  activeState: true
                  suppressedOrShelved: true
                  node: string
                  processArea: string
                  actiontime: string
                  otherFields: {}
                totalCount: 0
                continuationToken: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageModel'
              example:
                statusCode: 0
                message: string
                traceId: string
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageModel'
              example:
                statusCode: 0
                message: string
                traceId: string
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageModel'
              example:
                statusCode: 0
                message: string
                traceId: string
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageModel'
              example:
                statusCode: 0
                message: string
                traceId: string
        '429':
          description: Too Many Requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageModel'
              example:
                statusCode: 0
                message: string
                traceId: string
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageModel'
              example:
                statusCode: 0
                message: string
                traceId: string
        '504':
          description: Gateway Timeout
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageModel'
              example:
                statusCode: 0
                message: string
                traceId: string
      x-source: https://api.equinor.com/developer/apis/iiot-ae-api-v1/operations/GetEvents?api-version=2022-04-01-preview
      tags:
      - Events
  /events/{facility}/count:
    get:
      operationId: GetCounts
      summary: Retrieves a list of count for events by priority.
      description: Retrieves a list of count for events by priority. Parameters can be used to select a subset of events. Max 6 months timewindow.
      parameters:
      - name: facility
        in: path
        required: true
        description: Name of the facility which to retrieve data.
        schema:
          type: string
      - name: startTime
        in: query
        required: false
        description: Format - date-time (as date-time in RFC3339). Start of data window. Defaults to 1970. Rounded down to nearest interval.
        schema:
          type: string
      - name: endTime
        in: query
        required: false
        description: Format - date-time (as date-time in RFC3339). End of data window. Defaults to now. Rounded up to nearest interval.
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CountDto'
              example:
                statusCode: 0
                message: string
                traceId: string
                items:
                - timestamp: string
                  count: 0
                  priority: 0
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageModel'
              example:
                statusCode: 0
                message: string
                traceId: string
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageModel'
              example:
                statusCode: 0
                message: string
                traceId: string
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageModel'
              example:
                statusCode: 0
                message: string
                traceId: string
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageModel'
              example:
                statusCode: 0
                message: string
                traceId: string
        '429':
          description: Too Many Requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageModel'
              example:
                statusCode: 0
                message: string
                traceId: string
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageModel'
              example:
                statusCode: 0
                message: string
                traceId: string
        '504':
          description: Gateway Timeout
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageModel'
              example:
                statusCode: 0
                message: string
                traceId: string
      x-source: https://api.equinor.com/developer/apis/iiot-ae-api-v1/operations/GetCounts?api-version=2022-04-01-preview
      tags:
      - Events
components:
  schemas:
    EventModel:
      type: object
      properties:
        timestamp:
          type:
          - string
          - 'null'
          format: date-time
        sourceName:
          type:
          - string
          - 'null'
        description:
          type:
          - string
          - 'null'
        eventType:
          type:
          - string
          - 'null'
        eventCategory:
          type:
          - string
          - 'null'
        message:
          type:
          - string
          - 'null'
        severity:
          type:
          - integer
          - 'null'
          format: int32
        priority:
          type:
          - integer
          - 'null'
          format: int32
        condition:
          type:
          - string
          - 'null'
        alarmState:
          type:
          - string
          - 'null'
        ackedState:
          type:
          - boolean
          - 'null'
        activeState:
          type:
          - boolean
          - 'null'
        suppressedOrShelved:
          type:
          - boolean
          - 'null'
        node:
          type:
          - string
          - 'null'
        processArea:
          type:
          - string
          - 'null'
        actiontime:
          type:
          - string
          - 'null'
          format: date-time
        otherFields:
          type:
          - object
          - 'null'
          additionalProperties: {}
      additionalProperties: false
    CountDto:
      type: object
      properties:
        statusCode:
          type:
          - integer
          - 'null'
          format: int32
        message:
          type:
          - string
          - 'null'
        traceId:
          type:
          - string
          - 'null'
        items:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/CountModel'
      additionalProperties: false
    CountModel:
      type: object
      properties:
        timestamp:
          type:
          - string
          - 'null'
          format: date-time
        count:
          type:
          - integer
          - 'null'
          format: int32
        priority:
          type:
          - integer
          - 'null'
          format: int32
      additionalProperties: false
    MessageModel:
      type: object
      properties:
        statusCode:
          type: integer
          format: int32
        message:
          type:
          - string
          - 'null'
        traceId:
          type:
          - string
          - 'null'
      additionalProperties: false
    EventDto:
      type: object
      properties:
        statusCode:
          type:
          - integer
          - 'null'
          format: int32
        message:
          type:
          - string
          - 'null'
        traceId:
          type:
          - string
          - 'null'
        items:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/EventModel'
        totalCount:
          type:
          - integer
          - 'null'
          format: int64
        continuationToken:
          type:
          - string
          - 'null'
      additionalProperties: false
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
x-generated-from: apim-developer-portal-data
x-source: https://api.equinor.com/api-details#api=iiot-ae-api-v1
x-generated-note: The anonymous APIM export at https://api.equinor.com/developer/apis/iiot-ae-api-v1?export=true&format=openapi%2Bjson returns this document with empty paths; paths were assembled verbatim (by script) from the same portal's anonymous operations and schemas endpoints, saved in openapi/_original/.
